[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_hello_world = "7LULzYja5GZKq7Kcy6TgVCJYpHgFVyQmQ4c1FwZqVNMj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"